version: "3.7"

services:
  BAM-Game:
    image: BAM-Game:0.1.0
    build:
      context: . # relative to docker-compose.yml
      dockerfile: Dockerfile
    ports:
      - "5050:80"
    restart: unless-stopped
